# Flags
DEV_LAYOUT = False
RPI = False
ENGINE = True

# Sensors
SENSOR_THRESHOLD_LOW = 12200
SENSOR_THRESHOLD_HIGH = 13600

# Themes
# Green
THEME_WHITE = "#eeeed5"
THEME_BLACK = "#7d945d"

# Brown
# THEME_WHITE = "#f0d9b5"
# THEME_BLACK = "#b58863"