# Flags
DEV_LAYOUT = False
RPI = False

# Sensors
SENSOR_THRESHOLD_LOW = 13320
SENSOR_THRESHOLD_HIGH = 14000

# Themes
# Green
THEME_WHITE = "#eeeed5"
THEME_BLACK = "#7d945d"

# Brown
# THEME_WHITE = "#f0d9b5"
# THEME_BLACK = "#b58863"